paths:
  /v1:
    get:
      operationId: AppController_getHello
      x-google-backend:
        address: ${api_backend}
        path_translation:
          - APPEND_PATH_TO_ADDRESS
      parameters: []
      responses:
        '200':
          description: ''
  /v1/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '201':
          description: ''
  /v1/auth/refresh:
    post:
      operationId: AuthController_refreshTokens
      parameters: []
      responses:
        '201':
          description: ''
  /v1/users/{id}:
    get:
      operationId: UsersController_getUser
      parameters:
        - name: id
          required: true
          in: path
          type: string
      responses:
        '200':
          description: ''
  /v1/users:
    get:
      operationId: UsersController_listUsers
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: API Gateway + Cloud Run
  description: Sample API on APIGateway with a Cloud Run backend
  version: 1.0.0
  contact: {}
tags: []
swagger: '2.0'
definitions: {}
x-components: {}
