paths:
  /:
    get:
      operationId: AppController_getHello
      x-google-backend:
        address: ${api_backend}
        path_translation:
          - APPEND_PATH_TO_ADDRESS
      parameters: []
      responses:
        '200':
          description: ''
  /test:
    get:
      operationId: AppController_getTest
      parameters: []
      responses:
        '200':
          description: ''
  /auth/signup:
    post:
      operationId: AuthController_signup
      parameters:
        - required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/SignupArgsDto'
      responses:
        '201':
          description: ''
      consumes:
        - application/json
  /auth/signin:
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '201':
          description: ''
  /auth/refresh:
    post:
      operationId: AuthController_refreshTokens
      parameters: []
      responses:
        '201':
          description: ''
  /auth/signout:
    post:
      operationId: AuthController_signout
      parameters: []
      responses:
        '200':
          description: ''
  /auth/signin/google:
    get:
      operationId: AuthController_signinWithGoogle
      parameters: []
      responses:
        '200':
          description: ''
  /auth/google/callback:
    get:
      operationId: AuthController_googleAuthRedirect
      parameters: []
      responses:
        '200':
          description: ''
  /users:
    post:
      operationId: UsersController_createUser
      parameters:
        - required: true
          name: body
          in: body
          schema:
            $ref: '#/definitions/CreateUserDto'
      responses:
        '201':
          description: ''
      consumes:
        - application/json
    get:
      operationId: UsersController_listUsers
      parameters: []
      responses:
        '200':
          description: ''
  /users/{id}:
    get:
      operationId: UsersController_getUser
      parameters:
        - name: id
          required: true
          in: path
          type: string
      responses:
        '200':
          description: ''
info:
  title: API Gateway + Cloud Run
  description: Sample API on APIGateway with a Cloud Run backend
  version: 1.0.0
  contact: {}
tags: []
swagger: '2.0'
definitions:
  SignupArgsDto:
    type: object
    properties: {}
  CreateUserDto:
    type: object
    properties: {}
x-components: {}
